pipeline {
    agent any 
        environment {
            IMAGE_TAG = "${BUILD_NUMBER}"
        }

        stages{
            stage ('Checkout'){
                steps{
                    git credentialsId : 'jenkins-cicd-github'
                    url: 'https://github.com/devops-course-siva/jenkins-projects'
                    branch: 'main'
                }
            }
            stage('Build') {
                steps{
                    script{
                        sh '''
                        echo 'Building a Docker Image'
                        docker build -t sivanagu2607/cicd-e2e:${BUILD_NUMBER} .
                        '''
                        }
                    }
                }
            stage ('Push') {
                steps{
                    script{
                        sh '''
                        echo 'Pushing the artifacts to docker'
                        docker push  sivanagu2607/cicd-e2e:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        //     stage('checkout k8s manifest SCM'){
        //         steps{
        //             git credentialsId : ''
        //             url: 'https://github.com/devops-course-siva/jenkins-projects'
        //             branch : 'main'
        //         }
        //     }
        //     stage('Update k8s manifest & push to repo'){
        //     steps{
        //         script{
        //             withCredentials([usernamePassword(credentialsId: 'jenkins-cicd-github', passwordVariable: 'GIT_PASSWORD', usernameVariable:'GIT_USERNAME')]){
        //                 sh '''
        //                 cat deploy.yaml
        //                 sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
        //                 cat deploy.yaml
        //                 git add deploy.yaml
        //                 git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
        //                 git remote -v
        //                 git push https://github.com/devops-course-siva/jenkins-projects.git HEAD:main

        //                 '''
        //             }
                
        //         }
        //     }
        // }
    }
}


